name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements-test.txt

      - name: Run tests with pytest
        run: |
          pytest backend/test.py -v
          
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    needs: test 
    environment: "1"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Copy project files via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "."  # Copy entire project
          target: ${{ secrets.DEPLOY_PATH }}
          overwrite: true
          rm: true  # Remove the deployment-package folder after copy
      
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e  # Exit on error
            cd ${{ secrets.DEPLOY_PATH }}
            
            echo "=== Stopping existing containers ==="
            docker compose -f docker-compose.yml down || true
            
            echo "=== Building and starting new containers ==="
            docker compose -f docker-compose.yml up -d --build
            
            echo "=== Checking services ==="
            docker compose -f docker-compose.yml ps
            
            echo "=== Deployment completed successfully ==="
            
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'
